(() => {
"use strict";

const BOOKING_URL = "https://irs.thsrc.com.tw/IMINT/";
const STORE = "thsr-quick-booking-flagship-v1";
const PREFS = "thsr-quick-booking-prefs-v1";
const stations = ["南港","台北","板橋","桃園","新竹","苗栗","台中","彰化","雲林","嘉義","台南","左營"];
const statusList = ["計畫中","待開賣","待訂票","已訂位","已付款","已取票","已取消"];
const $ = id => document.getElementById(id);

let state = { trips: [], targetId: "" };
let sentReminders = new Set();
let wakeLock = null;
let audioCtx = null;

function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function nowISO(){return new Date().toISOString()}
function localDateTimeValue(d){const z=n=>String(n).padStart(2,"0");return d.getFullYear()+"-"+z(d.getMonth()+1)+"-"+z(d.getDate())+"T"+z(d.getHours())+":"+z(d.getMinutes())}
function fmtDate(v){if(!v)return"";const d=new Date(v.length===10?v+"T00:00:00":v);if(Number.isNaN(d.getTime()))return v;return new Intl.DateTimeFormat("zh-TW",{year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function fmtDateTime(v){if(!v)return"";const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return new Intl.DateTimeFormat("zh-TW",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(d)}
function saveState(){localStorage.setItem(STORE,JSON.stringify(state))}
function loadState(){try{const v=JSON.parse(localStorage.getItem(STORE)||"null");if(v&&Array.isArray(v.trips))state=v}catch(e){}}
function currentTarget(){return state.trips.find(t=>t.id===state.targetId)||null}
function passengerTotal(t){return ["adultCount","childCount","seniorCount","disabledCount","studentCount"].reduce((sum,k)=>sum+(Number(t[k])||0),0)}
function passengerText(t){return [["全票",t.adultCount],["孩童票",t.childCount],["敬老票",t.seniorCount],["愛心票",t.disabledCount],["大學生",t.studentCount]].filter(x=>Number(x[1])>0).map(x=>x[0]+"×"+x[1]).join("、")||"未設定"}
function tripSummary(t){if(!t)return"";return ["【台灣高鐵快速訂票行程】","行程："+t.origin+" → "+t.destination,"去程："+t.departDate+" "+t.departTime,t.tripType==="roundtrip"?"回程："+t.returnDate+" "+t.returnTime:"","乘客："+passengerText(t),"車廂："+t.carClass,t.saleOpenAt?"開賣提醒："+fmtDateTime(t.saleOpenAt):"",t.reservationCode?"訂位代號："+t.reservationCode:"",t.paymentDeadline?"付款期限："+fmtDateTime(t.paymentDeadline):"",t.note?"備註："+t.note:""].filter(Boolean).join("\n")}
async function copyText(text,statusEl,okText="已複製"){if(!text){if(statusEl)statusEl.textContent="目前沒有可複製的資料";return false}try{await navigator.clipboard.writeText(text)}catch(e){const ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove()}if(statusEl){statusEl.textContent="✓ "+okText;setTimeout(()=>statusEl.textContent="",2200)}return true}
function validateTrip(t){if(!t.origin||!t.destination)return"請選擇出發站與到達站";if(t.origin===t.destination)return"出發站與到達站不可相同";if(!t.departDate||!t.departTime)return"請填寫去程日期與時間";if(t.tripType==="roundtrip"&&(!t.returnDate||!t.returnTime))return"去回程請填寫回程日期與時間";if(t.tripType==="roundtrip"&&new Date(t.returnDate+"T"+t.returnTime)<new Date(t.departDate+"T"+t.departTime))return"回程時間不可早於去程";const total=passengerTotal(t);if(total<1)return"至少需有 1 位乘客";if(t.tripType==="roundtrip"&&total>5)return"依官方網路訂票規則，去回程每一方向最多 5 張，請將乘客總數調整為 5 人以下";if(t.tripType==="oneway"&&total>10)return"依官方網路訂票規則，單筆交易至多 10 張乘車票";return""}

function fillStations(){const options='<option value="">請選擇</option>'+stations.map(s=>`<option value="${s}">${s}</option>`).join("");$("origin").innerHTML=options;$("destination").innerHTML=options}
function collectForm(){return{id:$("editingId").value||uid(),tripName:$("tripName").value.trim(),tripType:$("tripType").value,origin:$("origin").value,destination:$("destination").value,departDate:$("departDate").value,departTime:$("departTime").value,returnDate:$("returnDate").value,returnTime:$("returnTime").value,carClass:$("carClass").value,saleOpenAt:$("saleOpenAt").value,adultCount:Number($("adultCount").value)||0,childCount:Number($("childCount").value)||0,seniorCount:Number($("seniorCount").value)||0,disabledCount:Number($("disabledCount").value)||0,studentCount:Number($("studentCount").value)||0,status:$("tripStatus").value,reservationCode:$("reservationCode").value.trim(),paymentDeadline:$("paymentDeadline").value,note:$("note").value.trim()}}
function clearForm(){$("editingId").value="";$("tripName").value="";$("tripType").value="oneway";$("origin").value="";$("destination").value="";$("departDate").value="";$("departTime").value="09:00";$("returnDate").value="";$("returnTime").value="18:00";$("carClass").value="不限";$("saleOpenAt").value="";$("adultCount").value=1;["childCount","seniorCount","disabledCount","studentCount"].forEach(id=>$(id).value=0);$("tripStatus").value="計畫中";$("reservationCode").value="";$("paymentDeadline").value="";$("note").value="";toggleReturnFields();updatePassengerHint();$("formStatus").textContent=""}
function loadTripToForm(id){const t=state.trips.find(x=>x.id===id);if(!t)return;Object.keys(t).forEach(k=>{const el=$(k);if(el)el.value=t[k]});$("editingId").value=t.id;$("tripType").value=t.tripType||"oneway";toggleReturnFields();updatePassengerHint();$("tripFormCard").scrollIntoView({behavior:"smooth",block:"start"});$("formStatus").textContent="正在編輯："+(t.tripName||t.origin+" → "+t.destination)}
function toggleReturnFields(){const show=$("tripType").value==="roundtrip";document.querySelectorAll(".return-field").forEach(el=>el.style.display=show?"flex":"none")}
function updatePassengerHint(){const t=collectForm();const total=passengerTotal(t);const limit=t.tripType==="roundtrip"?5:10;$("passengerHint").textContent=`目前共 ${total} 位；此行程模式建議上限 ${limit} 位。`}
function saveTrip(){const t=collectForm();const err=validateTrip(t);if(err){$("formStatus").textContent=err;return}const i=state.trips.findIndex(x=>x.id===t.id);if(i>=0){t.createdAt=state.trips[i].createdAt;t.updatedAt=nowISO();state.trips[i]=t}else{t.createdAt=nowISO();t.updatedAt=nowISO();state.trips.push(t)}if(!state.targetId)state.targetId=t.id;saveState();$("formStatus").textContent=i>=0?"✓ 行程已更新":"✓ 行程已新增";clearForm();renderAll()}
function deleteTrip(id){const t=state.trips.find(x=>x.id===id);if(!t)return;if(!confirm(`確定刪除「${t.tripName||t.origin+" → "+t.destination}」？`))return;state.trips=state.trips.filter(x=>x.id!==id);if(state.targetId===id)state.targetId=state.trips[0]?.id||"";saveState();renderAll()}
function duplicateTrip(id){const t=state.trips.find(x=>x.id===id);if(!t)return;const copy={...t,id:uid(),tripName:(t.tripName||t.origin+"-"+t.destination)+" 複製",status:"計畫中",reservationCode:"",paymentDeadline:"",createdAt:nowISO(),updatedAt:nowISO()};state.trips.push(copy);saveState();renderAll()}
function setTarget(id){state.targetId=id;sentReminders.clear();saveState();renderAll();$("targetCard").scrollIntoView({behavior:"smooth",block:"start"})}
function setStatus(id,status){const t=state.trips.find(x=>x.id===id);if(!t)return;t.status=status;t.updatedAt=nowISO();saveState();renderAll()}
function statusBadgeClass(status){if(["已付款","已取票"].includes(status))return"badge-green";if(["待開賣","待訂票","已訂位"].includes(status))return"badge-amber";if(status==="已取消")return"badge-neutral";return"badge-blue"}

function renderTrips(){const filter=$("statusFilter").value,targetId=state.targetId;let list=state.trips.slice();if(filter!=="all")list=list.filter(t=>t.status===filter);$("tripCount").textContent=state.trips.length+" 筆";$("tripList").innerHTML="";if(!list.length){$("tripList").innerHTML='<div class="empty">尚無符合條件的行程。</div>';return}list.forEach(t=>{const div=document.createElement("div");div.className="trip"+(t.id===targetId?" target":"");const title=esc(t.tripName||"未命名行程"),route=esc(t.origin)+" → "+esc(t.destination);const travel=`${esc(fmtDate(t.departDate))} ${esc(t.departTime)}`+(t.tripType==="roundtrip"?` ｜ 回程 ${esc(fmtDate(t.returnDate))} ${esc(t.returnTime)}`:"");const sale=t.saleOpenAt?`開賣提醒：${esc(fmtDateTime(t.saleOpenAt))}`:"未設定開賣提醒";const res=t.reservationCode?` ｜ 訂位代號：${esc(t.reservationCode)}`:"";div.innerHTML=`<div><div class="trip-title">${title}</div><div class="route-line">${route}</div><div class="trip-meta">${travel}<br>${sale}<br>${esc(passengerText(t))} ｜ ${esc(t.carClass)}${res}</div><div class="trip-badges"><span class="badge ${statusBadgeClass(t.status)}">${esc(t.status)}</span>${t.id===targetId?'<span class="badge badge-red">目前主攻</span>':""}</div></div><div class="trip-actions"><button class="btn soft mini action-target" data-id="${t.id}" ${t.id===targetId?"disabled":""}>${t.id===targetId?"主攻中":"設為主攻"}</button><button class="btn accent mini action-book" data-id="${t.id}">官方訂票</button><button class="btn soft mini action-edit" data-id="${t.id}">編輯</button><button class="btn soft mini action-dup" data-id="${t.id}">複製行程</button><select class="action-status" data-id="${t.id}">${statusList.map(s=>`<option value="${s}" ${s===t.status?"selected":""}>${s}</option>`).join("")}</select><button class="btn danger mini action-delete" data-id="${t.id}">刪除</button></div>`;$("tripList").appendChild(div)});document.querySelectorAll(".action-target").forEach(b=>b.onclick=()=>setTarget(b.dataset.id));document.querySelectorAll(".action-book").forEach(b=>b.onclick=()=>bookTrip(b.dataset.id));document.querySelectorAll(".action-edit").forEach(b=>b.onclick=()=>loadTripToForm(b.dataset.id));document.querySelectorAll(".action-dup").forEach(b=>b.onclick=()=>duplicateTrip(b.dataset.id));document.querySelectorAll(".action-delete").forEach(b=>b.onclick=()=>deleteTrip(b.dataset.id));document.querySelectorAll(".action-status").forEach(s=>s.onchange=()=>setStatus(s.dataset.id,s.value))}
function renderTarget(){const t=currentTarget(),panel=$("targetPanel");if(!t){$("targetRoute").textContent="尚未設定行程";$("targetMeta").textContent="先在下方新增行程。";$("targetStatusBadge").textContent="尚未設定";$("targetStatusBadge").className="badge badge-neutral";["cdDays","cdHours","cdMinutes","cdSeconds"].forEach(id=>$(id).textContent="--");$("countdownLabel").textContent="尚未設定開賣提醒時間";panel.className="target-panel";renderQuickCopy();return}$("targetRoute").textContent=t.origin+" → "+t.destination;$("targetMeta").textContent=[t.tripName,"去程 "+fmtDate(t.departDate)+" "+t.departTime,t.tripType==="roundtrip"?"回程 "+fmtDate(t.returnDate)+" "+t.returnTime:"",passengerText(t),t.carClass].filter(Boolean).join(" ｜ ");$("targetStatusBadge").textContent=t.status;$("targetStatusBadge").className="badge "+statusBadgeClass(t.status);renderCountdown();renderQuickCopy()}
function renderCountdown(){const t=currentTarget(),panel=$("targetPanel");if(!t||!t.saleOpenAt){["cdDays","cdHours","cdMinutes","cdSeconds"].forEach(id=>$(id).textContent="--");$("countdownLabel").textContent="未設定開賣／搶票提醒時間";panel.className="target-panel";return}const ms=new Date(t.saleOpenAt).getTime()-Date.now();if(["已付款","已取票"].includes(t.status)){["cdDays","cdHours","cdMinutes","cdSeconds"].forEach(id=>$(id).textContent="00");$("countdownLabel").textContent="此行程已完成主要訂票流程";panel.className="target-panel done";return}if(ms<=0){["cdDays","cdHours","cdMinutes","cdSeconds"].forEach(id=>$(id).textContent="00");$("countdownLabel").textContent="設定的開賣／搶票時間已到";panel.className="target-panel open";triggerReminder("open",0,t);return}const total=Math.floor(ms/1000),d=Math.floor(total/86400),h=Math.floor((total%86400)/3600),m=Math.floor((total%3600)/60),s=total%60;$("cdDays").textContent=String(d).padStart(2,"0");$("cdHours").textContent=String(h).padStart(2,"0");$("cdMinutes").textContent=String(m).padStart(2,"0");$("cdSeconds").textContent=String(s).padStart(2,"0");if(ms<=10*60*1000){panel.className="target-panel ready";$("countdownLabel").textContent="已進入開賣前 10 分鐘準備模式"}else{panel.className="target-panel";$("countdownLabel").textContent="距離設定的開賣／搶票時間"}[["30",30,$("rem30").checked],["10",10,$("rem10").checked],["5",5,$("rem5").checked],["1",1,$("rem1").checked]].forEach(([key,min,on])=>{if(on&&ms<=min*60000&&ms>(min*60000-1500))triggerReminder(key,min,t)})}
function renderQuickCopy(){const t=currentTarget(),box=$("quickCopyList");box.innerHTML="";if(!t){box.innerHTML='<div class="empty">設定主攻行程後，這裡會出現快速複製欄位。</div>';return}const items=[["出發站",t.origin],["到達站",t.destination],["去程日期",t.departDate],["去程時間",t.departTime],["乘客",passengerText(t)],["車廂",t.carClass]];if(t.tripType==="roundtrip")items.push(["回程日期",t.returnDate],["回程時間",t.returnTime]);if(t.reservationCode)items.push(["訂位代號",t.reservationCode]);items.forEach(([label,value])=>{const div=document.createElement("div");div.className="quick";div.innerHTML=`<div><b>${esc(label)}</b><span>${esc(value||"未設定")}</span></div><button class="btn soft mini">複製</button>`;div.querySelector("button").onclick=()=>copyText(value,$("targetStatus"),"已複製"+label);box.appendChild(div)})}
function renderAll(){renderTrips();renderTarget()}
async function bookTrip(id){const t=state.trips.find(x=>x.id===id);if(!t)return;await copyText(tripSummary(t),$("targetStatus"),"已複製行程摘要");window.open(BOOKING_URL,"_blank","noopener")}
async function bookTarget(){const t=currentTarget();if(!t){$("targetStatus").textContent="請先設定主攻行程";return}await bookTrip(t.id)}
function sortBySale(){state.trips.sort((a,b)=>{const A=a.saleOpenAt?new Date(a.saleOpenAt).getTime():Infinity,B=b.saleOpenAt?new Date(b.saleOpenAt).getTime():Infinity;return A-B});saveState();renderTrips()}
function sortByTravel(){state.trips.sort((a,b)=>new Date(a.departDate+"T"+a.departTime)-new Date(b.departDate+"T"+b.departTime));saveState();renderTrips()}
function regularOpenReference(){if(!$("departDate").value){$("formStatus").textContent="請先選擇去程日期";return}const d=new Date($("departDate").value+"T00:00:00");d.setDate(d.getDate()-28);$("saleOpenAt").value=localDateTimeValue(d);$("formStatus").textContent="已填入一般29日規則參考值；週五／週六延伸及特殊疏運請再查官方公告"}

function savePrefs(){localStorage.setItem(PREFS,JSON.stringify({rem30:$("rem30").checked,rem10:$("rem10").checked,rem5:$("rem5").checked,rem1:$("rem1").checked,notify:$("notifyToggle").checked,vibrate:$("vibrateToggle").checked,wake:$("wakeToggle").checked,sound:$("soundToggle").checked}))}
function loadPrefs(){try{const p=JSON.parse(localStorage.getItem(PREFS)||"{}");["rem30","rem10","rem5","rem1"].forEach(id=>{if(id in p)$(id).checked=!!p[id]});if("notify"in p)$("notifyToggle").checked=!!p.notify;if("vibrate"in p)$("vibrateToggle").checked=!!p.vibrate;if("wake"in p)$("wakeToggle").checked=!!p.wake;if("sound"in p)$("soundToggle").checked=!!p.sound}catch(e){}}
async function requestNotify(){if(!("Notification"in window)){ $("reminderStatus").textContent="此瀏覽器不支援網頁通知";return}const p=await Notification.requestPermission();$("notifyToggle").checked=p==="granted";savePrefs();$("reminderStatus").textContent=p==="granted"?"✓ 已允許通知":"通知權限未開啟"}
function beep(times=1){try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();for(let i=0;i<times;i++){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.frequency.value=880;g.gain.value=.07;o.start(audioCtx.currentTime+i*.35);o.stop(audioCtx.currentTime+i*.35+.18)}}catch(e){}}
function triggerReminder(key,mins,t){const token=t.id+":"+key;if(sentReminders.has(token))return;sentReminders.add(token);const title=mins===0?"高鐵搶票時間到了":`距離高鐵搶票提醒還有 ${mins} 分鐘`,body=t.origin+" → "+t.destination+"｜"+fmtDate(t.departDate)+" "+t.departTime;if($("notifyToggle").checked&&"Notification"in window&&Notification.permission==="granted"){try{new Notification(title,{body,icon:"./icon-192.png"})}catch(e){}}if($("vibrateToggle").checked&&navigator.vibrate)navigator.vibrate(mins===0?[300,120,300,120,500]:[180,100,180]);if($("soundToggle").checked)beep(mins===0?3:1);$("reminderStatus").textContent=title+"｜"+body;setTimeout(()=>$("reminderStatus").textContent="",4500)}
function testReminder(){if($("notifyToggle").checked&&"Notification"in window&&Notification.permission==="granted"){try{new Notification("高鐵極速訂票提醒測試",{body:"提醒功能測試成功",icon:"./icon-192.png"})}catch(e){}}if($("vibrateToggle").checked&&navigator.vibrate)navigator.vibrate([180,100,180]);if($("soundToggle").checked)beep(1);$("reminderStatus").textContent="✓ 已執行提醒測試"}
async function updateWake(){savePrefs();if($("wakeToggle").checked){if("wakeLock"in navigator){try{wakeLock=await navigator.wakeLock.request("screen");$("reminderStatus").textContent="✓ 已啟用保持螢幕喚醒";wakeLock.addEventListener("release",()=>{wakeLock=null})}catch(e){$("reminderStatus").textContent="無法啟用螢幕喚醒，可能是瀏覽器限制"}}else $("reminderStatus").textContent="此瀏覽器不支援保持螢幕喚醒"}else if(wakeLock){try{await wakeLock.release()}catch(e){}wakeLock=null}}
document.addEventListener("visibilitychange",async()=>{if(document.visibilityState==="visible"&&$("wakeToggle").checked&&!wakeLock)await updateWake()});

function icsEsc(s){return String(s||"").replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function icsUTC(v){const d=v instanceof Date?v:new Date(v),z=n=>String(n).padStart(2,"0");return d.getUTCFullYear()+z(d.getUTCMonth()+1)+z(d.getUTCDate())+"T"+z(d.getUTCHours())+z(d.getUTCMinutes())+z(d.getUTCSeconds())+"Z"}
function downloadICS(filename,summary,start,end,description,url,alarms=[]){const valarms=alarms.map(m=>`BEGIN:VALARM\r\nTRIGGER:-PT${m}M\r\nACTION:DISPLAY\r\nDESCRIPTION:${icsEsc(summary)}\r\nEND:VALARM`).join("\r\n");const content=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//THSR Quick Booking PWA//ZH-TW\r\nCALSCALE:GREGORIAN\r\nBEGIN:VEVENT\r\nUID:thsr-${Date.now()}@quick-booking\r\nDTSTAMP:${icsUTC(new Date())}\r\nDTSTART:${icsUTC(start)}\r\nDTEND:${icsUTC(end)}\r\nSUMMARY:${icsEsc(summary)}\r\nDESCRIPTION:${icsEsc(description)}\r\nURL:${url}\r\n${valarms}\r\nEND:VEVENT\r\nEND:VCALENDAR`;const blob=new Blob([content],{type:"text/calendar;charset=utf-8"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function targetSaleCalendar(){const t=currentTarget();if(!t||!t.saleOpenAt){$("targetStatus").textContent="請先設定主攻行程的開賣提醒時間";return}const start=new Date(t.saleOpenAt),end=new Date(start.getTime()+15*60000);downloadICS("高鐵開賣提醒.ics","高鐵開賣｜"+t.origin+"→"+t.destination,start,end,tripSummary(t),BOOKING_URL,[30,10,5,1]);$("targetStatus").textContent="✓ 已產生開賣提醒行事曆檔"}
function targetTravelCalendar(){const t=currentTarget();if(!t)return;const start=new Date(t.departDate+"T"+t.departTime),end=new Date(start.getTime()+2*60*60000);downloadICS("高鐵乘車行程.ics","高鐵｜"+t.origin+"→"+t.destination,start,end,tripSummary(t),BOOKING_URL,[60,30]);$("targetStatus").textContent="✓ 已產生乘車行程行事曆檔"}

function exportData(){const payload={version:"flagship-v1",exportedAt:nowISO(),state,prefs:localStorage.getItem(PREFS)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json;charset=utf-8"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="高鐵極速訂票PWA_備份.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);$("backupStatus").textContent="✓ 已匯出備份"}
function importData(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d?.state||!Array.isArray(d.state.trips))throw new Error("bad");state=d.state;saveState();if(d.prefs)localStorage.setItem(PREFS,d.prefs);loadPrefs();renderAll();$("backupStatus").textContent="✓ 備份已匯入"}catch(e){$("backupStatus").textContent="匯入失敗：不是本 PWA 的有效備份"}};r.readAsText(file)}
function resetAll(){if(!confirm("確定清除所有高鐵行程與設定？此動作無法復原。"))return;localStorage.removeItem(STORE);localStorage.removeItem(PREFS);state={trips:[],targetId:""};clearForm();loadPrefs();renderAll();$("backupStatus").textContent="已清除全部資料"}

function bind(){
  $("tripType").onchange=()=>{toggleReturnFields();updatePassengerHint()};
  ["adultCount","childCount","seniorCount","disabledCount","studentCount"].forEach(id=>$(id).addEventListener("input",updatePassengerHint));
  document.querySelectorAll(".preset").forEach(b=>b.onclick=()=>{$("origin").value=b.dataset.from;$("destination").value=b.dataset.to});
  $("swapStations").onclick=()=>{const a=$("origin").value;$("origin").value=$("destination").value;$("destination").value=a};
  $("saveTrip").onclick=saveTrip;$("clearForm").onclick=clearForm;$("regularOpenRef").onclick=regularOpenReference;
  $("statusFilter").onchange=renderTrips;$("sortSale").onclick=sortBySale;$("sortTravel").onclick=sortByTravel;
  $("targetBookNow").onclick=bookTarget;$("targetCopySummary").onclick=()=>copyText(tripSummary(currentTarget()),$("targetStatus"),"已複製行程摘要");$("targetSaleCalendar").onclick=targetSaleCalendar;$("targetTravelCalendar").onclick=targetTravelCalendar;$("goTarget").onclick=()=>$("targetCard").scrollIntoView({behavior:"smooth",block:"start"});
  ["rem30","rem10","rem5","rem1","notifyToggle","vibrateToggle","soundToggle"].forEach(id=>$(id).addEventListener("change",savePrefs));$("wakeToggle").addEventListener("change",updateWake);$("requestNotify").onclick=requestNotify;$("testReminder").onclick=testReminder;
  $("exportData").onclick=exportData;$("importDataBtn").onclick=()=>$("importFile").click();$("importFile").onchange=e=>{if(e.target.files[0])importData(e.target.files[0])};$("resetAll").onclick=resetAll;
  let deferredPrompt=null;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e});$("installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else $("installHelp").style.display=$("installHelp").style.display==="block"?"none":"block"};
}
function init(){fillStations();loadState();loadPrefs();bind();clearForm();renderAll();if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));setInterval(renderCountdown,1000)}
init();
})();
